### PR TITLE
Finalising all bs-react-native docs

### PR DESCRIPTION
**Pull request by vnovick**
Finalising all API docs migration. No docs left in Rebolt. 

Issue #267

### CODE REVIEW

**Comment by vnovick** [comment]
Pushed all other docs here too closing #295

**Comment by czystyl** [comment]
Great job @vnovick !!! 

I'm going to check what's is wrong with building doc

**Comment by grabbou** [comment]
The failure is unrelated to this PR so let's merge it and see what happens. It's really odd issue. 

@czystyl have you checked the PR content-wise? Do you have any comments?

**Comment by vnovick** [comment]
@wokalski , We want to merge this PR. Can you please remove required label from docs?
Docs are failing on bunch of other PRs too, but it is not related to branch [check @grabbou comment](https://github.com/reasonml-community/bs-react-native/pull/294#issuecomment-444987036)

**Pull request merged**
