### PR TITLE
Fix invalid json in bsconfig.json

### PR DESCRIPTION
**Pull request by MoOx**
Current json is not valid.
I think it's better to keep it valid.

I could set up [prettier](https://github.com/prettier/prettier) if you are interested, to prevent this kind of "issues".

### CODE REVIEW

**Comment by wokalski** [comment]
I don't understand the pros of this one? Do you do anything particular with bsconfigs?

**Comment by MoOx** [comment]
I just opened it in atom and saw syntax errors (json lint). Valid json does not accept trailing comma. I don't do anything special with it, but it could be incorrectly parsed "someday" by a valid json parser.

**Comment by arnarthor** [comment]
It's not invalid syntax, bsconfig uses JSON5 so this is fine. I actually like trailing commas everywhere makes it easier to add more stuff later on. That said, I don't have a strong opinion on this, but I'd prefer to keep them.

**Comment by wokalski** [comment]
Alrighty, closing this one then.

**Comment by MoOx** [comment]
Make sense. Will remove my json lint plugin then haha.

**Pull request closed without merging**
