### PR TITLE
[WIP] Create manual namespace

### PR DESCRIPTION
**Pull request by czystyl**
**Please do not merge yet.**

It's a proposal of how we can make a namespace for oDoc. 

All files ware changed by `find and replace`.

### CODE REVIEW

**Comment by grabbou** [comment]
CC: @wokalski 

BTW, @czystyl, I can see some changes to the overall styling of the file - did you run it through refmt? What version?

Wondering if that's a new update or you are on a older one.

**Comment by czystyl** [comment]
I installed all the tools today. 

BTW I wondering why my refmt change from `(` to `}` 🤔

**Comment by grabbou** [comment]
I think for now we will just do manual links in-between different pages untill this gets fixed.

**Comment by wokalski** [comment]
@czystyl it's a reformat update. I suggest we have this in a separate PR.

**Comment by grabbou** [comment]
Thank you for your effort @czystyl, it's been a really great journey to do it! Unfortunately, after giving it another thought, I decided to stick to namespaces and fix links on the API reference for now.

Hopefully, we can do something about that going forward.

**Pull request closed without merging**
