### PR TITLE
Allow Modal#supportedOrientations to take an array of possible orientations instead of a single one

### PR DESCRIPTION
**Pull request by leomayleomay**
According to Facebook's document on `Modal`, the `supportedOrientations` should be able to take an array of possible orientations, https://facebook.github.io/react-native/docs/modal.html#supportedorientations, the binding doesn't reflect that, this PR is to fix that

### CODE REVIEW

**Comment by arnarthor** [comment]
Ugh, the request changes mark is so negative on github 😞 sorry about that

**Comment by leomayleomay** [comment]
@arnarthor haha, no problem at all, just wondering where the `Rebuild` button is in UI

image

**Comment by arnarthor** [comment]
No I mean locally. Just run `yarn build` locally. The compiled JS should be commited into the PR 👍

**Comment by leomayleomay** [comment]
@arnarthor done updating the JS file :)

**Comment by wokalski** [comment]
@leomayleomay I'm not sure. @arnarthor probably has a better idea.

**Comment by arnarthor** [comment]
@leomayleomay a new release has been shipped with the next tag. `yarn add bs-react-native@next` should do it 💥

**Comment by arnarthor** [comment]
There are some breaking changes due too color interpolation that you'll need to address when updating.

**Comment by leomayleomay** [comment]
@arnarthor cheers, :)

**Pull request merged**
