### PR TITLE
fix(bs-react-native): fix path name

### LINKED ISSUE #469: Installing using git url
As per the documentation it says to use `bs-react-native` namespace to refer to the git installation
```
{
  // ...
  "bs-dependencies": [
    // BsReactNative, current "stable" bindings
    "bs-react-native/bs-react-native",
    // ReactNative, WIP on zero-cost bindings (require bs-platform 5.0.0 & and reason-react hooks branch)
    "bs-react-native/reason-react-native"
  },
  // When used from git with the following path, bs-platform will use path that won't be working
  // (because deps are pointing to folder in folder)`
  // Your bundler (metro or webpack) will say that it can find `bs-react-native/whatever` and/or
  // `reason-react-native/whatever`
  // which is correct because it should be `bs-react-native/bs-react-native/whatever` / `bs-react-native/reason-react-native/whatever`
  // the trick below will correct path in generated JavaScript files
  // and will just need to be removed when you won't use git directly anymore
  "js-post-build": {
    "cmd": "./node_modules/bs-react-native/git-monorepo-usage-trick"
  }
}
```

where when installing with yarn the destination is actually `node_modules/bs-react-native-monorepo` so I gotta do a `mv` to rename properly. I'm not sure if I'm doing something wrong or the docs are misleading.

Let me know if I can send a PR for this!

### PR DESCRIPTION
**Pull request by fakenickels**
Fixes #469

### CODE REVIEW

**Comment by fakenickels** [comment]
Testing here before turning clicking in `Ready for review`

**Comment by MoOx** [comment]
Maybe we should instead adjust the git-monorepo-trick to make it clearer?

**Comment by fakenickels** [comment]
This one worked fine, but I agree with you @MoOx. Maybe it's less confusing keeping the `-monorepo`

**Comment by fakenickels** [comment]
I think this is even better because it allows people to have both the monorepo and the npm package at once

**Comment by fakenickels** [comment]
I am testing it now

**Pull request merged**
