### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by grabbou**
Initial structure of the documentation, framework for building and running it, Animated documentation.

### CODE REVIEW

**Comment by grabbou** [comment]
screen shot 2018-09-22 at 18 28 54

Here's how it looks like now. I am slowly migrating Rebolt documentation over to `rei` files and working with @ostera (and others) to figure out all remaining issues.

Will be working on it from Monday on.

**Comment by grabbou** [comment]
I temporarily disabled namespaces as it was adding `-BsReactNative` to every module name. Ideally, we should think of a way to change that title.

**Comment by grabbou** [comment]
Main page for `Animated` is finished with examples and descriptions straight from Rebolt documentation. Working on documenting module Easing, Interpolation, Value and ValueXY as well as the home page and this can be merged to master as a bare-bones documentation.

While working on the documentation for the Animated module I've noticed few improvements to the general API surface. Please check `animatedRe.rei` to make sure you are aware of that and you think it's a good step.

**Comment by grabbou** [comment]
To make review process easier, please find the screenshot of the entire `Animated` description below:
screencapture-localhost-8080-bsreactnative-animatedre-2018-09-23-15_39_08

**Comment by knowbody** [comment]
@grabbou maybe try deploying your branch to [Netlify](https://www.netlify.com/docs/continuous-deployment/#branches-deploys), so you can see your changes every time you push

**Comment by grabbou** [comment]
Yeah, it's a good idea! Eventually, I would love to have an automated script that deploys documentation everytime we merge something to master. 

It's quite similar to what React Native currently does. 

I am not sure whether this can be done with Travis as I am much more familiar with Circle. If there are no strong objections, I would probably send another PR later today that updates the CI to perform such action.

**Comment by knowbody** [comment]
Netlify has this option and it's quite easy to set up

**Comment by grabbou** [comment]
Sounds great. Will definitely look into setting it up as a part of this PR.

**Comment by grabbou** [comment]
This is ready for review as far as documentation of the `Animated` module and little changes performed to `Animated` interface.

Decided to remove legacy references (that were previously marked as deprecated). The "upgrade" path is super easy and requires running search & replace operation on the codebase. We will explicitly list all the changes in the changelog which shouldn't make it a problem at all.

Also removed few internal methods (part of Value module) that were not meant to be used externally and could potentially cause confusion as far as what API to use when e.g. animating a node.

Waiting for Netlify to be granted access to this organization. Once accepted, this PR can be merged as a "base" for other documentation PRs. We have quite a few pages to document, including writing a good homepage too.

**Comment by grabbou** [comment]
The documentation itself is copy-paste from Rebolt documentation + improvements where needed. Added links in-between different modules, values etc. to make it easier to navigate. 

Note: `odoc` itself is still very experimental but it's cool we can get it run at that stage.

**Comment by grabbou** [comment]
Here's a preview: https://practical-knuth-fdb0a7.netlify.com/bsreactnative/animatedre-bsreactnative/ - simply drag & dropped latest `docs` folder from my machine.

Note: Home page is currently blank and doesn't include an index. Please ignore that fact for the time being.

**Comment by grabbou** [comment]
Todo:
- [x] Rewrite project's readme with ReasonReact-like structure and make list for contributors
- [  ] Fix status page and add proper links there
- [  ] Improve homepage with things we removed from Readme
- [  ] Deploy to Netlify automatically / somewhere else and update domain in the readme
- [  ] Add FAQ section and link it
- [  ] Add COC to the readme
- [  ] Add `all-contributors` to the readme

**Comment by grabbou** [comment]
Unfortunately, after doing some research, we need to use CI. We need OCaml and few other libraries to actually build the documentation. Seems impossible on Netlify.

**Comment by Krizzu** [comment]
@grabbou Nice work 👏 
In circle config, you can also move 

```   
 working_directory: ~/bs-react-native
 docker:
      - image: circleci/node:8.0
```

part to aliases at the top

**Comment by grabbou** [comment]
Good catch @krizzu, doing it!

**Comment by grabbou** [comment]
@ulrikstrid Yeah, I would be happy to do so - can we follow up on Discord or somewhere else? Would like to understand the benefits. Also, internally, we are using Azure so this looks like a natural feature.

So far, I'll stick to Circle as a part of this PR so we can get GH pages built.

**Comment by grabbou** [comment]
I will work on the following two TODOs in a separate PR:
- [ ] Fix status page and add proper links there
- [ ] Improve homepage with things we removed from Readme

Rest is done and ready to be merged.

**Comment by grabbou** [comment]
Removed Travis integration from this repository and set CircleCI as a designated CI as far as running on PRs and being required to pass before anything gets merged.

**Comment by grabbou** [comment]
All-contributors list has been added as per #247.

**Pull request merged**
