### PR TITLE
Add stickyHeaderIndices to flatlist

### PR DESCRIPTION
**Pull request by Arnarkari93**

### CODE REVIEW

**Comment by czystyl** [comment]
Good job @Arnarkari93! But before we merge it, we need to fix the docs.

**Comment by Arnarkari93** [comment]
I was not able to run the docs I tried the thing in the contributing guide but it did not work. 

I get a bunch of errors like this 
```
odoc: internal error, uncaught exception:
      Failure("File \"./lib/bs/src/timePickerAndroid-BsReactNative.cmti\":\nnot an interface")
      Raised at file "stdlib.ml", line 33, characters 17-33
      Called from file "cmdliner_term.ml", line 25, characters 19-24
      Called from file "cmdliner.ml", line 116, characters 32-39
```

**Comment by vnovick** [comment]
@Arnarkari93 , check that you are on correct version of odoc.
https://github.com/ocaml/odoc#using-odoc-with-bucklescriptreason

Also if you want to be up to date with docs you can merge from this branch: https://github.com/reasonml-community/bs-react-native/tree/migrating-api-docs

This is the branch with competed docs that will be merged to master.

**Comment by felicianotech** [comment]
The status checks above didn't report and I have a hunch why. This PR is a "forked" PR from an outside repo to this repo. By default, public projects on CircleCI have a setting called "Build forked pull requests" turned off. I'd check to see if this is off and if it is, turn it on if that's what you want.

There's another related setting that disabled build secrets for forked PRs. That should also be off and you 99% likely want to keep that one off for security reasons.

I hope that helped. Let me know if there're any other questions CircleCI related. :+1:

**Comment by MoOx** [comment]
@Arnarkari93 could you fix the conflicts by rebasing & re-running bs?
Btw about the doc issue you mentionned, it's because you need to `opam switch create 4.02.3+buckle-master` before `opam install odoc`.
I will make a PR to adjust the contributing doc!

**Comment by MoOx** [comment]
@Arnarkari93 you should use "git rebase", not merge, to avoid this weird diff we are getting (in addition to resolving the conflict).

**Comment by Arnarkari93** [comment]
I am trying to learn it, I will do my best

**Comment by MoOx** [comment]
@Arnarkari93 in short you can do the following, assuming you are in your git repo (you fork)

- git remote add upstream https://github.com/reasonml-community/bs-react-native.git
- git checkout upstream/master
- git pull
- git checkout feature/stickHeaderIndices-flatlist-2
- git rebase upstream master
- *handle the mess by following what git advise*
- when you have rebased, without any wip you can: git push --force

This should update the pr automatically.

There is probably a shorter way to does this, but it should work

**Comment by Arnarkari93** [comment]
I tried to rebase, It was a mess. I just created a [new PR](https://github.com/reasonml-community/bs-react-native/pull/317).

**Pull request closed without merging**
