### PR TITLE
Add `focus` and `blur` methods to <TextInput />

### PR DESCRIPTION
**Pull request by Trancever**
This PR adds missing blur and focus methods to TextInput module.

### CODE REVIEW

**Comment by wokalski** [comment]
`refmt`  :D. We should probably standarize refmt version in the repo. Anyway, looks good but I'd like to wait for #235 to land first so that we can deal with the conflicts in this PR. (That one is from an external contributor and I don't want them to deal with this.)

**Comment by grabbou** [comment]
@Trancever please update your PR against master and factor in latest changes as performed in #235 (handling undefined values and boolean).

**Comment by grabbou** [comment]
Please ignore my previous comment, going to rebase and refactor this right now.

**Comment by grabbou** [comment]
Rebased this branch and added missing methods. I believe this is now ready to be merged.

**Comment by wokalski** [comment]
It is good to merge 🙂

**Pull request merged**
