### PR TITLE
Fix FlatList scrollToOffset

### PR DESCRIPTION
**Pull request by phated**
I've been using these changes in my project otherwise `scrollToOffset` wasn't working.

### CODE REVIEW

**Comment by grabbou** [comment]
What do you mean by `it wasn't working`? You were not able to provide float values? Or the method wasn't working at all

**Comment by grabbou** [comment]
After chatting with the core team, we figured that offset can have float values (at least on iOS)

**Comment by phated** [comment]
To clarify "doesn't work" - the method being called didn't exist and when I changed it, the onScroll handler receives a float in the event that can't be passed directly to `scrollToOffset`.

Regarding floats - I'm using floats on android 7.1.2 and it works perfectly.  If I round the float, the view doesn't scroll to the exact position again.

**Comment by grabbou** [comment]
Going to merge it as I confirmed float to be the correct payload.

**Comment by wokalski** [comment]
Thank you guys!

**Comment by grabbou** [comment]
Thanks @wokalski! Wanted to merge it, but eventually realized it was impossible from my mobile device :(

**Pull request merged**
