### PR TITLE
0.8.0 release

### PR DESCRIPTION
**Pull request by arnarthor**
I need to open this as a PR to get the release onto master 😄

v0.8.0 is out on npm with the latest master

### CODE REVIEW

**Comment by arnarthor** [comment]
Interesting, I've forgotten to do this for a while now.

0.7.0 is the latest npm version. It went out on either 31. April or 1. May

**Comment by wokalski** [comment]
Why are there three commits in this PR :D ?

**Comment by arnarthor** [comment]
It seems I haven't pushed an updated package.json for a while. I've been updating the lib regularly on npm but completely forgotten to push it 😬 . This puts it back on track so from now on it should be kept up to date 😄

**Comment by wokalski** [comment]
@arnarthor yeah, but my question is, can't we squash them?

**Comment by arnarthor** [comment]
Done @wokalski 👍

**Pull request merged**
