### PR TITLE
Fix section type within renderSectionHeader and renderSectionFooter

### LINKED ISSUE #90: SectionList `renderSectionHeader` is passed an incorrect type
Seems as though SectionList is passed a `Js.t {. section: section 'a }`, though in javascript we're passed `Js.t {. section: jsSection 'a }`.

This means that accessing the key of a section is undefined:

```
renderSectionHeader=(
  fun js => {
    /* js.section is an object so `key` is accessed by: */
    let sec = js##section;
    let key = sec##key; /* but this is a type error; sec is of type section 'a in reason */
  }
)
```

### PR DESCRIPTION
**Pull request by tonyhb**
Wrap the prop to SectionList with an optional function that ensures
to pass a section('item) instead of a jsSection('item).

Fixes #90

### CODE REVIEW

**Comment by arnarthor** [comment]
Could you merge master into this just to make sure it compiles (although I don't doubt that it does). I'll feel better if the PR is green 💚

**Comment by wokalski** [comment]
@arnarthor please review & merge if it's ok 👍

**Comment by nhducit** [comment]
please remember to close issue https://github.com/reasonml-community/bs-react-native/issues/104 when this PR is merged

**Comment by arnarthor** [comment]
closes #104

**Pull request merged**
