### PR TITLE
Make private types under TypesRN and Props public

### PR DESCRIPTION
**Pull request by jamieparkinson**
Resolves https://github.com/reasonml-community/bs-react-native/issues/153

Let me know if you think an interface file is necessary too 🙂

### CODE REVIEW

**Comment by wokalski** [comment]
@jamieparkinson awesome. One question, can we change `TypesRN` to `Types`?

**Comment by jamieparkinson** [comment]
@wokalski hmmm, do you think doing that might cause some confusion when (as is likely/recommended) people are using `open BsReactNative`? `Types` is a generic enough name that I think there's an argument for including `RN`, perhaps as a prefix rather than a suffix though. Up to you!

**Comment by wokalski** [comment]
I think that we have namespacing precisely in order to have precise names without suffixes and other things. I'm rooting for `Types`.

**Comment by wokalski** [comment]
Also, since these are just types, only `rei` is needed IIRC. We don't need `.re`.

**Comment by jamieparkinson** [comment]
Yeah, point taken re namespacing and good tip re `.rei` - have updated. (apologies for weird authorship on last commit, am using my old laptop with outdated git/ssh config)

**Pull request merged**
