### PR TITLE
Update bs-platform and reason-react + fix deprecations

### PR DESCRIPTION
**Pull request by eldh**
Currently when starting a new project using the installation instructions, you get some deprecation warnings due to usage of deprecated methods, specifically `Js.Result` and `ReasonReact.stringToElement`.

This PR updates `bs-platform` and `reason-react` and fixes the deprecation warnings.

### CODE REVIEW

**Comment by eldh** [comment]
Thanks :)

**Comment by wokalski** [comment]
Great, thanks for they review and the PR!

Please do merge it next time @MoOx @ulrikstrid  😄

**Comment by bsr203** [comment]
@wokalski can you make a release with this changes. With the latest `reason-react`, build fails

```
  /Users/.../node_modules/bs-react-native/src/components/text.re 105:24-50

  103 ┆ switch (value) {
  104 ┆ | Some(string) =>
  105 ┆   Array.append([|ReasonReact.stringToElement(string)|], children)
  106 ┆ | None => children
  107 ┆ },

```
appreciate your help.

**Comment by arnarthor** [comment]
Sure I'll make a release tomorrow @bsr203

**Comment by bsr203** [comment]
@arnarthor can you please make a release. As `stringToElement` is removed in the current version of ReasonReact, need to patch it whenever add new dependency. thanks.

**Pull request merged**
