### PR TITLE
Remove links to missing documentation for deprecated components and APIs

### PR DESCRIPTION
**Pull request by sgny**
Links to `BackAndroid`, `ListView` and `ListViewDataSource` should probably be removed because
• documentation does not exist
• bindings don't exist and
• they are deprecated

### CODE REVIEW

**Comment by cknitt** [comment]
@MoOx Do you think it would make sense to add bindings for these deprecated components?

Surely no one would use these for new projects - is it possible that people are using them in old projects they want to migrate?

**Comment by MoOx** [comment]
Maybe we could leave this things so people that would look for those won't ask question?
And only remove them when they are officially removed from RN?

**Comment by sgny** [comment]
> Maybe we could leave this things so people that would look for those won't ask question?
> And only remove them when they are officially removed from RN?

Should I simply add one-liners explaining that these are deprecated and `BackHandler`, `FlatList`, etc. should be used instead

**Comment by MoOx** [comment]
That can be cool

**Comment by sgny** [comment]
`CameraRoll.md` also needed to meet `prettier`.

**Comment by MoOx** [comment]
(@sgny you can run `yarn format` at the root of the repo - but with the hook in place, we should need that only when we update the formating tools)

**Comment by sgny** [comment]
> (@sgny you can run `yarn format` at the root of the repo - but with the hook in place, we should need that only when we update the formating tools)

`yarn format` does not match `.rei` files, should they not be?

**Comment by MoOx** [comment]
They should be, that my mistake :)

**Pull request merged**
