### PR TITLE
Add missing inverted prop to FlatList and SectionList.

### PR DESCRIPTION
**Pull request by mcanobbio**
I add the inverted prop to FlatList component

### CODE REVIEW

**Comment by grsabreu** [comment]
Closes https://github.com/reasonml-community/bs-react-native/issues/176

**Comment by grsabreu** [comment]
Thanks for contributing @mcanobbio, can you also add the `inverted` param in `SectionList`?

**Comment by mcanobbio** [comment]
Ok, I will do that @grsabreu

**Comment by grsabreu** [comment]
Awesome, merged @mcanobbio

**Pull request merged**
