### PR TITLE
Add travis-ci

### LINKED ISSUE #18: Continuous Integration
Developing an OSS project is not too sustainable without some kind of Continuous Integration. I'm not sure how to approach it because FFI by definition is hard to test. Maybe some integration tests using the UI Explorer app?

### PR DESCRIPTION
**Pull request by saschatimme**
This should hopefully catch all compile errors at least :)

- [x]  I still have to setup travis-ci (I don't have proper rights atm).

Closes #18

### CODE REVIEW

**Comment by wokalski** [comment]
We should build `RNTester`, too.

**Comment by saschatimme** [comment]
Not sure how to configure travis, because we need a second npm install etc.

**Comment by arnarthor** [comment]
You could of course introduce something like Lerna to have RNTester be a separate package, which would then never be published while the src code would be. 

That way you could easily run build for both RNTester and the lib itself. But it of course adds overhead to the project.

**Comment by saschatimme** [comment]
I think we can avoid to publish RNTester if we just add a `.npmignore`. I'm not sure Lerna works for us since bucklescript can only build files which are at the same level as the root or below and note above.

**Comment by saschatimme** [comment]
Let's move the discussion to #54

**Pull request merged**
