### PR TITLE
Add props to FlatList

### PR DESCRIPTION
**Pull request by arnarthor**

### CODE REVIEW

**Comment by saschatimme** [comment]
I think there is nothing in it what could trigger a runtime error (as we had once previously). So this should be fine.

**Comment by wokalski** [comment]
if I have a prop and it has no effect it's also a runtime error, for the user.

**Comment by arnarthor** [comment]
These props all come from either VirtualizedList or ScrollView, which makes me think if FlatList should be functor based, but either way I'm pretty sure these props have been there for a pretty long time, just not documented under the FlatList section.

**Comment by wokalski** [comment]
It's good to merge if they were in RN `^0.46.0`

**Comment by arnarthor** [comment]
Awesome I'll check and merge if that's the case 👍

**Comment by arnarthor** [comment]
Verified that this was all in React-Native 0.45.x 👍 merging this.

I don't have permission to publish new versions, this is not urgent on our end though, we've now vendored this into our project for simpler contributions and support for ourselves.

**Comment by saschatimme** [comment]
@arnarthor I made you an admin here and make you an owner at npm. So all the power is now also in your hand 💪

**Pull request merged**
