### PR TITLE
Move RNTester examples from Rebolt.

### LINKED ISSUE #223: Update RNTester with new examples
Rebolt's version of RNTester did have few more examples - migrate them.

### PR DESCRIPTION
**Pull request by Trancever**
Closes #223

### CODE REVIEW

**Comment by grabbou** [comment]
Going to run it just to double check everything works as expected. Would be awesome to get it as an Expo app one day (or similar), so that we can embed some of these within the documentation.

Thank you for porting it over!

**Comment by grabbou** [comment]
I think we should have a nicer playground with better examples and error handling, but going to merge this one for now. 

Ultimately, we want similar to RNTester experience showcasing all the components. Might be worth talking to our designers too!

**Comment by Trancever** [comment]
@grabbou Sorry, i had to overlook this issue with ImagePicker.. What's the status of this PR? Can we merge it or something still has to be done?

**Comment by grabbou** [comment]
It's done, was waiting for tests to pass last week. Will be working on a new release. 

In the meantime, we need to reorganise a bit and split into two, sub-teams, as there's work to be done with navigation too.

**Comment by wokalski** [comment]
@grabbou Re navigation: Are you planning to do anything else with it than renaming Rebolt to Bucklescript? It'd be cool if there was sort of ReboltNavigationView module which exposes the raw view primitives to use so that it's easy/possible to implement alternative nav APIs.

**Pull request merged**
