### PR TITLE
Fix odoc install on Circle-CI

### PR DESCRIPTION
**Pull request by MoOx**
`[I don't know what I am doing.gif]`

### CODE REVIEW

**Comment by MoOx** [comment]
Seems I fixed it. Any thoughts about how I did it? @wokalski @grabbou 
Note that I used another docker image (found this in facebook/reason repo) and it seems to be faster (at least to get the opam/odoc ready to go).

**Comment by wokalski** [comment]
This seems great @MoOx. I'm giving an approval, but I'd like to hear what @ulrikstrid thinks since he's most knowledgable when it comes to odoc here.

**Comment by ulrikstrid** [comment]
I only used odoc with dune and esy, but @ostera might be interested in this repo

**Comment by MoOx** [comment]
I used this docker image following a discussion with him (dm on discord). Not that he advised this precise solution but he pointed out that the issue we were facing was because of the opam version (1.2.2 before this pr). We need opam 2.x apparently.
This docker image might be a good choice as it's fast & reliable.
I would like @grabbou feedback as it seems he setup the previous circle-ci config.

**Comment by ulrikstrid** [comment]
I think this is good as it is. I hope we can get better integrating of odoc and bsb soon so we shouldn't spend more time than necessary on this imo.

**Comment by MoOx** [comment]
Going to merge then. If we want to improve we can :)

**Pull request merged**
