### PR TITLE
Upgrade to Reason 3 and enable namespaces

### PR DESCRIPTION
**Pull request by arnarthor**
This covers the changes me and @wokalski discussed on discord regarding upgrades for namespaces, Reason 3 and changing reason-react to a peer dependency.

Do you have permission to submit under @reasonml-community @saschatimme? I might also be mistaken on how organization namespaced packages work, and I wasn't sure if the bsconfig name should be `react-native` or `@reasonml-community/react-native`. I thought it made sense that it should be `react-native` based on my knowledge on namespaces.

Correct me if I'm wrong here 👍 

Regarding the review it's probably wise to read through the last 2 commits separately. The first commit is just the automated script to update the syntax.

### CODE REVIEW

**Comment by saschatimme** [comment]
I don’t think I have the permissions. @chenglou could you help with that?

**Comment by chenglou** [comment]
Just added both of you to the npm reasonml-communtity org =)

**Comment by wokalski** [comment]
So the next task now is removing the ReactNative module and hiding the private modules.

**Comment by arnarthor** [comment]
Yeah that sounds good @wokalski 👍 

I can work on that tonight unless you want to take it

**Comment by arnarthor** [comment]
We're already vendoring this in our project so I can then make sure everything works properly as well before publishing 👌

**Comment by wokalski** [comment]
We’re vendoring it too. I’m going to sleep so feel free to take it.

**Pull request merged**
