### PR TITLE
WIP: Add InputAccessoryView bindings

### PR DESCRIPTION
**Pull request by kepi74**

### CODE REVIEW

**Comment by grabbou** [comment]
Hey, thanks for this contribution! Do you plan to submit any remaining pieces of work to flag this as a non WIP and allow review?

**Comment by kepi74** [comment]
I'm sorry to left it long time without any progress. I have a bug in my
code and have to resolve it, to have working example. I'll look on it
tomorrow and eventually ask for help at discord channel to close this PR

Dne po 10. 9. 2018 18:49 uživatel Mike Grabowski <notifications@github.com>
napsal:

**Comment by grabbou** [comment]
Oh, thank you! I am here if you need any help :) Feel free to reach out to me via Discord (Callstack) or ReasonML (react) channel. Preparing release and want to make sure it all lands.

Make sure to rebase from master as we have removed some `Js.Undefined` etc., it will be easier to review later :)

**Comment by grabbou** [comment]
Going to close it for now - let's reopen once you get a bit more time and rebase with latest changes! And... if you need any help, just let me know!

**Pull request closed without merging**
