### PR TITLE
Fixes webview event types

### PR DESCRIPTION
**Pull request by Rikkiabb**
Fixes bindings for event types in WebView

### CODE REVIEW

**Comment by ulrikstrid** [comment]
Should this be modelled with deriving abstract instead?

**Comment by Rikkiabb** [comment]
Sure, how would you do that?

**Comment by ulrikstrid** [comment]
The type would look something like this:
```ocaml
[@bs.deriving abstract]
type t = {
  [@bs.option] url: string,
  [@bs.option] title: string,
  [@bs.option] loading: bool,
  [@bs.option] canGoBack: bool,
  [@bs.option] canGoForward: bool
}
```
and then it can be used like this: `let config = t(~url: "https://google.com", ());`

**Comment by ulrikstrid** [comment]
I think this looks good cc @wokalski

**Comment by wokalski** [comment]
I think `/lib` hasn't been updated.

**Comment by wokalski** [comment]
Other than that, it's super mergeable 👍

**Comment by wokalski** [comment]
Thanks!

**Pull request merged**
