### PR TITLE
[WIP] Merging Rebolt v1 back to bs-react-native

### PR DESCRIPTION
**Pull request by knowbody**
#204 

Because our repo was cloned, and then the name was changed, etc. now I forked it to `knowbody/bs-react-native` set it as a remote to rebolt, pushed the changes and made this PR, all because I wanted to keep the whole history and contributors who contributed to Rebolt as well.

Let's chat here if there are things that should be changed etc. and I will try to make the changes accordingly so we can get it merged soon.

### CODE REVIEW

**Comment by knowbody** [comment]
This is just an initial PR with fixed conflicts. There are a few things that need changing that I can see already, i.e. CircleCI as `bs-react-native` uses Travis, we can remove circle

**Comment by wokalski** [comment]
@knowbody thank you for that. That's very very very appreciated. Can we split this into multiple PRs so that we can review? I'm leaving the order up to you, maybe you want to cherry pick, not sure. I think we can wrap it up pretty quickly though.

I have a few pieces of feedback already but I don't want to make it too chaotic so I'll be giving the feedback in related PRs.

**Comment by knowbody** [comment]
@wokalski yeah that's sounds good. Is there any specific way of dividing this PR into smaller PRs? i.e. API bindings, Component bindings, the rest?

**Comment by wokalski** [comment]
@knowbody maybe new bindings, modified bindings, doc `md`s + infra? I'm not sure what's the scope of the changes you did.

**Comment by wokalski** [comment]
I'm closing this one as per #204

**Pull request closed without merging**
