### PR TITLE
fix CameraRoll.saveToCameraRollOverrideType

### PR DESCRIPTION
**Pull request by sgny**
Prompted by #459

### CODE REVIEW

**Comment by MoOx** [comment]
I thing we should totally avoid this empty string.

**Comment by cknitt** [comment]
I am not sure about that. Avoiding the empty string can cause other mistakes when you copy a binding and forget to change the string. And it means more work...

**Comment by MoOx** [comment]
The opposite is valid: you can copy a binding & forget to update the non visible implicit string.
I thing it far more easy to forget about the empty string. 
I think Chenglou & other got a discussion about this and stopped to recommend empty string

**Comment by cknitt** [comment]
In our bindings, in >99%, the `""` is correct because we use the same name on the Reason side as on the JS side.

The remaining cases are those where we provide two or more bindings for the same function, like `xxx` and `xxxWithConfig`. In those cases you need to pay close attention on implementation and review. For the remaining 99.9% it is overkill to specify the function name again IMHO.

And by using the naming convention xxx**With**Yyy, it is easy to search for these cases in the code. I used this convention in all cases in my code. I think `saveToCameraRollOverrideType` is the only case where we don't have it, maybe we should change it to `saveToCameraRollWithType`.

**Comment by MoOx** [comment]
Fair enough.

`saveToCameraRollWithType` make sense then?

**Comment by MoOx** [comment]
Fair enough.

saveToCameraRollWithType make sense then.

**Pull request merged**
