### PR TITLE
Release v0.10.0-rc.0

### PR DESCRIPTION
**Pull request by grabbou**
Can't make a direct push, so making a PR. 

Pushed 0.10.0-rc.0 and tagged it as `next`. We will use this one to test `Rebolt` integration and many new features before promoting it to stable (similar to React Native lifecycle).

### CODE REVIEW

**Comment by wokalski** [comment]
the built has failed 😢

**Comment by grabbou** [comment]
Oh :(

What's the `push` build supposed to do? Can't find any log information in there. The `pr` one seems to be passing.

**Comment by wokalski** [comment]
btw, we dont' want to have direct pushes allowed. We are accepting everybody to have write access so this gives us at least some security.

**Comment by grabbou** [comment]
Yeah, I noticed. You could probably add me to `whitelisted` people with
push access to master, I am sure no-one would mind xd Either way, it's
fine. I can still push tags and make a release, so it's not that disturbing
as you'd think.

**Pull request merged**
