### PR TITLE
bind accessibilityHint and accessibilityLabel

### PR DESCRIPTION
**Pull request by Arnarkari93**

### CODE REVIEW

**Comment by arnarthor** [comment]
lol, github outage sure messed with me here

**Comment by Arnarkari93** [comment]
Just checking in... is there something blocking this from being merged?

**Comment by arnarthor** [comment]
Nope :shipit:

**Comment by arnarthor** [comment]
Hmm well, for some reason it hasn't built in CI yet. Could you try to push a new commit to see if CI triggers

**Comment by Arnarkari93** [comment]
Still won't trigger 🤔

**Comment by Arnarkari93** [comment]
close in favor of https://github.com/reasonml-community/bs-react-native/pull/298

**Pull request closed without merging**
